---
title: "Quant DO-MS"
author: "Single nPOP Melanoma, 1 Frame 300 ms method "
date: "11/29/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source('QuantQC_functions.R')


# Read in the path to DIA-NN file
 # need to download from this link for example: https://drive.google.com/drive/folders/1EBeHGCQksMt3jItFVPxf-POEYiXQ7mGs
data_path <- "report.tsv"


## Read in meta data (Just links raw file to inject well)
linker <- utils::read.csv('linker.csv')


#List your cell types
cell_types <- c('MEL','HEK')


### Read in cell isolation files from CellenONE and assign cell type
# These files are made in the folders generated from cell dispensing (they are xls but I convert to csv)

cell_type1 <- read.table(file = "CellenONE_Files/G1.csv", sep = ",", header = TRUE)
cell_type1$condition <- "G1"


cell_type2 <- read.table(file = "CellenONE_Files/S.csv", sep = ",", header = TRUE)
cell_type2$condition <- "S"

cell_type3 <- read.table(file = "CellenONE_Files/G2.csv", sep = ",", header = TRUE)
cell_type3$condition <- "G2"


all_cells <- rbind(cell_type1,cell_type2,cell_type3)

#CellenONE files for the pickup, these specify the cluster centers of each set
pickupPath1 <-'CellenONE_Files/Pickup_1_mock.txt' # For plate 1
pickupPath2 <- "CellenONE_Files/Pickup_2_mock.txt" # For plate 2

# field file specifying labeling scheme

labelPath <- "CellenONE_Files/Labels.fld"


Raw_data <- utils::read.delim(data_path)
Raw_data <- Raw_data %>% filter(Lib.PG.Q.Value < .05)

Raw_data <- Raw_data %>% left_join(linker, by = c('Run'))

ChQval <- .01
CV_thresh <- .6
cycle_length <- .4

carrier <- F # put true or false for if a carrier was used

plex_used <- c('0','4') # here put the mTRAQ channels that were used 


#Unique precursor ID
Raw_data$seqcharge <- paste0(Raw_data$Stripped.Sequence,Raw_data$Precursor.Charge)

# this grabs the mTRAQ tag used (may need to be adjusted if using different multiplexing tag)
Raw_data$plex <- substr(Raw_data$Precursor.Id[1:nrow(Raw_data)], 10, 10)

# Filter report for relevant channels
Raw_data <- Raw_data %>% filter(plex %in% plex_used)

```

# Results {.tabset}

```{r Pre_proccess, include=FALSE}

## mapping cell data to raw data
cellenOne_data <- analyzeCellenONE(all_cells,pickupPath2,pickupPath1,labelPath)

# if using plex/scopeDIA samples are injected into 2 different plates,
# there are 16 fields and samples from 1-8 go into plate 1, 9-16 go into plate 2
cellenOne_data$plate <- NA
cellenOne_data$plate[cellenOne_data$field > 8] <- 2
cellenOne_data$plate[cellenOne_data$field <= 8] <- 1

# Assigning mTRAQ tags to wells where label was picked up out of during prep
# Each tag was dispensed multiple times so maps to multiple wells of plate, numbers 1-8 below correspond to wells G1-G8 here
cellenOne_data$tag <- NA
cellenOne_data$tag[cellenOne_data$label %in% c('1','3','5','7')] <- '0'
cellenOne_data$tag[cellenOne_data$label %in% c('2','4','6','8')] <- '4'

# Create cell ID to match DIA-NN report
cellenOne_data$ID <- paste0(cellenOne_data$injectWell,cellenOne_data$plate,cellenOne_data$tag)
cellenOne_data_small <- cellenOne_data %>% dplyr::select(ID,diameter,sample,tag)

# Analogous cell ID made from DIA-NN report and linker file
Raw_data$ID <- paste0(Raw_data$Well,Raw_data$Plate,Raw_data$plex)
Raw_data$File.Name <- Raw_data$ID



# Create data frame that maps all cell types from cellenONE data to IDs from DIA-NN and 
# also specifies which channels are negative controls (i.e. no match to cell sorting data)
cellID <- unique(Raw_data$ID)
cellID <- as.data.frame(cellID)
colnames(cellID) <- 'ID'
cellID <- cellID %>% left_join(cellenOne_data_small,by = c('ID'))
cellID$sample[is.na(cellID$sample)==T] <- 'neg'



# Filter and save matricies for different QCs
Raw_data_no_filt <- Raw_data
Raw_data <- Raw_data %>% filter(Channel.Q.Value < ChQval)

Raw_data_lim <- Raw_data %>% dplyr::select(File.Name,Protein.Group,seqcharge,Ms1.Area)
Raw_data_lim_NF <- Raw_data_no_filt %>% dplyr::select(File.Name,Protein.Group,seqcharge,Ms1.Area)

Raw_data_lim.d <- dcast(Raw_data_lim,Protein.Group+seqcharge~File.Name,value.var = 'Ms1.Area')
Raw_data_lim_NF.d <- dcast(Raw_data_lim_NF,Protein.Group+seqcharge~File.Name,value.var = 'Ms1.Area')


```



## CellenONE_info

### Visualization of cells on slides 

```{r, echo=FALSE,fig.width = 13, fig.height = 14}

# print the cell IDs overlayed on the positions of the slide

ggplot(cellenOne_data, aes(x = dropXPos,y = dropYPos,color = sample,label = injectWell)) + 
   geom_point() + geom_text(hjust=0, vjust=0) +scale_y_reverse()+ facet_wrap(~field,ncol = 4)


```


```{r, echo=FALSE,fig.width = 13, fig.height = 14}
# print the mTRAQ labels overlayed on the positions of the slide

cellenOne_data$label[cellenOne_data$label %in% c(1,3,5,7)] <- 'D0'
cellenOne_data$label[cellenOne_data$label %in% c(2,4,6,8)] <- 'D4'
ggplot(cellenOne_data, aes(x = dropXPos,y = dropYPos,color = label)) + 
   geom_point() +scale_y_reverse()+ facet_wrap(~field,ncol = 4)
```

## Overview


### Negative control vs real cell statistics


```{r negative_ctrl, echo=FALSE, fig.height=, fig.width=11, message=FALSE, warning=FALSE}

#Compute CVs of cells and negative controls
CVm <- CVs(Raw_data_lim_NF.d,CV_thresh,cellID)
#CV_vs_Intens <- CVm[[1]] # plot showing CV vs protein intensity
Cell_CVs <- CVm[[2]] # plot showing median protein CV of cells and negative controls
cells_cvs_list <- CVm[[3]] # IDs of cells with median protein CVs
good_cells <- cells_cvs_list %>% filter(cvq < CV_thresh) # Get IDs of cells that pass threshold


## count the number of peptides in negative controls and single cells

# Negative controls
sum_neg <- colSums(Raw_data_lim.d[,intersect(colnames(Raw_data_lim.d),cellID$ID[cellID$sample == 'neg'])] > 0,na.rm = T)
neg_df <- as.data.frame(sum_neg)
colnames(neg_df) <- 'Number_precursors'
neg_df$type <- 'negative ctrl'

# Add in 0 peptides for negative controls that were totally filtered out
missing_neg <- (length(cellID$ID[cellID$sample == 'neg'])-nrow(neg_df))
for(i in 1:missing_neg){
  neg_df[nrow(neg_df) + 1,] = c(0,"negative ctrl")
}

# Single cells
sum_cell <- colSums(Raw_data_lim.d[,intersect(colnames(Raw_data_lim.d),cellID$ID[cellID$ID %in% good_cells$variable])] > 0,na.rm = T)

pos_df <- as.data.frame(sum_cell)
colnames(pos_df) <- 'Number_precursors'
pos_df$type <- 'single cells'


neg_vs_pos_DF <- rbind(pos_df,neg_df)
neg_vs_pos_DF$Number_precursors <- as.numeric(neg_vs_pos_DF$Number_precursors)

Numb_data_points <- ggplot(neg_vs_pos_DF, aes(x = Number_precursors, fill = type)) + geom_histogram(position = 'identity') + ggtitle('# precursors per sample (With channel Q value filter)')


Numb_data_points + Cell_CVs


```


### Protein and peptide numbers per cell


```{r Compile_Statistics, echo=FALSE,fig.width = 11, fig.height = 4.5}

rownames(Raw_data_lim.d) <- Raw_data_lim.d$seqcharge
rownames(Raw_data_lim_NF.d) <- Raw_data_lim_NF.d$seqcharge
protein_list <- Raw_data_lim.d$Protein.Group 

# Compile  number of peptides per cell with and without channel q value filter
cells_filt <- Raw_data_lim.d %>% dplyr::select(good_cells$variable)
cells_NF_filt <- Raw_data_lim_NF.d %>% dplyr::select(good_cells$variable)
numb_pep_filt <- colSums(cells_filt > 0,na.rm = T)
numb_pep_NF <- colSums(cells_NF_filt > 0,na.rm = T)
numb_pep <- as.data.frame(numb_pep_filt)
colnames(numb_pep) <- 'number_peptides'
numb_pep$filt <- 'Yes Channel Qval filter'
numb_pepnf <- as.data.frame(numb_pep_NF)
colnames(numb_pepnf) <- 'number_peptides'
numb_pepnf$filt <- 'No Channel Qval filter'
numb_pep <- rbind(numb_pep,numb_pepnf)

# Compile  number of proteins per cell with and without channel q value filter
#Max LFQ protein level
Raw_data_lim <- Raw_data_lim %>% filter(File.Name %in% good_cells$variable)
protein_mat <- diann_maxlfq(Raw_data_lim,sample.header = "File.Name",group.header = "Protein.Group",id.header = "seqcharge",quantity.header = "Ms1.Area")

#Max LFQ protein level
Raw_data_lim_NF <- Raw_data_lim_NF %>% filter(File.Name %in% good_cells$variable)
protein_mat_NF <- diann_maxlfq(Raw_data_lim_NF,sample.header = "File.Name",group.header = "Protein.Group",id.header = "seqcharge",quantity.header = "Ms1.Area")


numb_prot_filt <- colSums(protein_mat > 0,na.rm = T)
numb_prot_NF <- colSums(protein_mat_NF > 0,na.rm = T)
numb_prot <- as.data.frame(numb_prot_filt)
colnames(numb_prot) <- 'number_proteins'
numb_prot$filt <- 'Yes Channel Qval filter'
numb_protnf <- as.data.frame(numb_prot_NF)
colnames(numb_protnf) <- 'number_proteins'
numb_protnf$filt <- 'No Channel Qval filter'
numb_prot <- rbind(numb_prot,numb_protnf)

pep_number <- ggplot(numb_pep, aes(x = number_peptides, fill = filt)) + geom_histogram(bins = 30,position = 'identity',alpha = .5) + ggtitle('# precursors per sample') + rremove('legend') + xlab('# precursors/cell')


prot_number<- ggplot(numb_prot, aes(x = number_proteins, fill = filt)) + geom_histogram(bins = 30,position = 'identity',alpha = .5) + ggtitle('# proteins per sample') + xlab('# Proteins/cell')

pep_number+prot_number

```


### Data completness based on filtering (uses intersected subset of proteins from channel qval filtered data)


```{r completness_Statistics, echo=FALSE,fig.width = 11, fig.height = 4.5}

protein_mat_NF <- protein_mat_NF[rownames(protein_mat_NF)%in% rownames(protein_mat),]


## Compile statistics about cell and normalize
missingness_cell_filt <- colSums(is.na(protein_mat) == F)/nrow(protein_mat)
missingness_prot_filt <- rowSums(is.na(protein_mat)==F)/ncol(protein_mat)

# with no filtering
missingness_cell_nf <- colSums(is.na(protein_mat_NF) == F)/nrow(protein_mat_NF)
missingness_prot_nf <- rowSums(is.na(protein_mat_NF)==F)/ncol(protein_mat_NF)

missingness_prot_mat <- cbind(missingness_prot_nf,missingness_prot_filt)
colnames(missingness_prot_mat) <- c('No channel Filter', 'With Filter')
missingness_prot_mat <- melt(missingness_prot_mat)

missingness_cell_mat <- cbind(missingness_cell_nf,missingness_cell_filt)
colnames(missingness_cell_mat) <- c('No channel Filter', 'With Filter')
missingness_cell_mat <- melt(missingness_cell_mat)

mp <- ggplot(missingness_prot_mat, aes(x = value, fill = Var2)) + 
  geom_histogram(bins = 20,position = 'identity',alpha = .5) + ggtitle(paste0('Protein completness, ',nrow(protein_mat_NF),' proteins'))+rremove('legend') + xlab('# of a given protein quantified / # of cells')

mc <- ggplot(missingness_cell_mat, aes(x = value, fill = Var2)) + 
  geom_histogram(bins = 20,position = 'identity',alpha = .5) + ggtitle('Cell completness')+
  xlab('# of proteins in a cell / # proteins in matrix (across all cells)')

mp+mc

# Save for comparing cell diameter to protein amount
cell_sums <- log10(colSums(protein_mat,na.rm = T))


#mean_intense_prot <- rowMeans(protein_mat,na.rm = T)
#prot_info <- as.data.frame(sums)
#prot_info$complete <- missingness_prot
#vars_no_norm <- (rowVars(protein_mat,na.rm = T))


#Normalize protein level 
protein_mat_old <- Normalize(protein_mat,log = 'yes')
protein_mat <- Normalize_saad(protein_mat,log = 'yes')


#add more statistics
# cell_info$sum_norm <- colSums(protein_mat,na.rm = T)
# cell_info$sum_norm_old <-  colSums(protein_mat_old,na.rm = T)
# vars <- (rowVars(protein_mat,na.rm = T))
# prot_info$vars <- vars
# prot_info$vars_no_norm <- vars_no_norm
# prot_info$sum_norm <- (rowMedians(protein_mat,na.rm = T))



```

### Correlations between peptides mapping to protein compared to variance

```{r correlations_pep to prot, echo=FALSE,fig.width = 7, fig.height = 4.5}

#Compute correlations between peptides mapping to same protein
cells_filt_norm <- Normalize_saad(cells_filt,log = 'yes')
pep_cor <- Pep_cor(cells_filt_norm,protein_list)
pep_cor <- pep_cor %>% filter(Protein %in% rownames(protein_mat))
rownames(pep_cor) <- pep_cor$Protein
protein_mat_mult_pep <- protein_mat[pep_cor$Protein,]
pep_cor <- pep_cor[rownames(protein_mat_mult_pep),]
pep_cor$FC <- rowMeans(abs(protein_mat_mult_pep),na.rm = T)
pep_cor$FC[pep_cor$FC <= .4] <- .4
pep_cor$FC[pep_cor$FC > .4 & pep_cor$FC <= .8] <- .8
pep_cor$FC[pep_cor$FC > .8 & pep_cor$FC <= 1.2] <- 1.2
pep_cor$FC[pep_cor$FC > 1.2 & pep_cor$FC <= 2] <- 2
pep_cor$FC[pep_cor$FC > 2] <- 3
pep_cor$FC <- as.character(pep_cor$FC)

ggplot(pep_cor, aes(y = Cor, x = FC)) + geom_boxplot() + xlab('Mean abs(protein fold change)') +ylab('Correlation between peptides mapping to a protein')

```



```{r PCA, echo=FALSE, fig.height=4.5, fig.width=11, message=FALSE, warning=FALSE, include=TRUE}

#mapping labels for correting them with combat


#protein_mat <- filt.mat.cr(protein_mat,.9,.7)


#assign labels
batch_label  <- as.data.frame(colnames(protein_mat))
colnames(batch_label)[1] <- 'ID'
batch_label <- batch_label %>% left_join(cellID,by = c('ID'))


#batch_label$run <- substring(batch_label$cells,14,16)


sc.imp <- hknn(protein_mat,3)

sc.imp <- Normalize_saad_log(sc.imp)

# correct out label bias (not too bad in general but does need correcting)
sc.batch_cor <- ComBat(sc.imp, batch=factor(batch_label$tag))

sc.batch_cor <- Normalize_saad_log(sc.batch_cor)
# NAing imputed values post batch correction
#Ms1_extract3_no_imp <- Ms1_extract3
#Ms1_extract3_no_imp[is.na(Ms1_extract2_noImp)==T] <- NA

cor_mat <- cor(sc.batch_cor,use = 'pairwise.complete.obs')

sc.pca <- eigen(cor_mat)
scx<-as.data.frame(sc.pca$vectors)
percent_var <- sc.pca$values/sum(sc.pca$values)*100
colnames(scx)<-paste0("PC",1:ncol(scx))
scx$ID <-colnames(protein_mat)

scx <- scx %>% left_join(batch_label,by = c('ID'))

scx$prot <- cell_sums

lab_plot <- ggplot(scx,aes(x = PC1,y = PC2, color = tag)) + geom_point(size = 5) + theme_classic() + ggtitle('Label Bias')
intense_plot <-  ggplot(scx,aes(x = PC1,y = PC2, color = prot)) + geom_point(size = 5) + theme_classic()+ ggtitle('Cell Intensity')+
  scale_color_gradient2(midpoint = median(scx$prot,na.rm = T), low = "blue", mid = "white",high = "red",name = '')

ggplot(scx,aes(x = PC1,y = PC2, color = sample)) + geom_point(size = 5) + theme_classic()+ ggtitle('Cell Type') +
  xlab(paste0('PC1 ',round(percent_var[1]),'%'))+ylab(paste0('PC2 ',round(percent_var[2]),'%'))


lab_plot + intense_plot

ggplot(scx,aes(x = diameter,y = prot,color=sample)) + geom_point(size = 5) + theme_classic()+ ggtitle(paste0('Correlation = ',round(cor(scx$prot,scx$diameter,use = 'pairwise.complete.obs'),digits = 3)))+ylab('log10(Total Cell Intensity)')+xlab('Cell Diameter')



```
























```{r Plotting_Stats, echo=FALSE,fig.width = 11, fig.height = 4.5}


# prot_info <- prot_info %>% filter(is.na(vars) == F)
# Var_norm <- ggplot(prot_info,aes(x = log10(sums),y = log10(vars))) + geom_point() + 
#   theme_bw()  + ggtitle(paste0('No normalization, ',"Cor = ", round(cor(log10(prot_info$sums),log10(prot_info$vars),use = 'pairwise.complete.obs'),digits = 3))) + xlab('Mean Protein Intensity') + ylab('Protein Variance')+ theme(axis.title.x = element_text(size = 20),axis.title.y = element_text(size = 20),axis.text.x = element_text(size = 15),axis.text.y = element_text(size = 15))
# 
# Var_no_norm <-ggplot(prot_info,aes(x = log10(sums),y = log10(vars_no_norm))) + geom_point() + 
#   theme_bw() + ggtitle(paste0('After normalization, ' ,"Cor = ", round(cor(log10(prot_info$sums),log10(prot_info$vars_no_norm),use = 'pairwise.complete.obs'),digits = 3)))+ xlab('Mean Protein Intensity') + ylab('Protein Variance')+ theme(axis.title.x = element_text(size = 20),axis.title.y = element_text(size = 20),axis.text.x = element_text(size = 15),axis.text.y = element_text(size = 15))
# 
# Var_no_norm + Var_norm


```



```{r, echo=FALSE,fig.width = 11, fig.height = 4.5}

#Saads plots
# Norm_quality_pre_cell <-ggplot(cell_info,aes(x = log10(sum_no_norm),y = complete)) + geom_point() + ylab('% Completeness of proteins in cell')+ xlab('log10(summed Intensity of cell)')+ theme_bw()+ ggtitle(paste0('No normalization, Cor = ', round(cor(log10(cell_info$sum_no_norm),cell_info$complete,use = 'pairwise.complete.obs'),digits = 3))) +theme(axis.title.x = element_text(size = 15),axis.title.y = element_text(size = 15),axis.text.x = element_text(size = 10),axis.text.y = element_text(size = 10)) 
# 
# Norm_quality_post_cell_saad <-ggplot(cell_info,aes(x = (sum_norm),y = complete)) + geom_point() + theme_bw()+ ggtitle(paste0('New normalization, Cor = ', round(cor(cell_info$sum_norm,cell_info$complete,use = 'pairwise.complete.obs'),digits = 3))) + ylab('% Completeness of proteins in cell')+ xlab('log10(summed Intensity of cell)')+ theme(axis.title.x = element_text(size = 15),axis.title.y = element_text(size = 15),axis.text.x = element_text(size = 10),axis.text.y = element_text(size = 10))
# 
# Norm_quality_post_cell_old <-ggplot(cell_info,aes(x = (sum_norm_old),y = complete)) + geom_point() + ggtitle(paste0('Old normalization, Cor = ', round(cor(cell_info$sum_norm_old,cell_info$complete,use = 'pairwise.complete.obs'),digits = 3)))+ theme_bw() + theme(axis.title.x = element_text(size = 15),axis.title.y = element_text(size = 15),axis.text.x = element_text(size = 10),axis.text.y = element_text(size = 10))
# 
# Norm_quality_pre_cell + Norm_quality_post_cell_old + Norm_quality_post_cell_saad
```



```{r, echo=FALSE,fig.width = 11, fig.height = 4.5}

# Norm_quality_pre_prot <-ggplot(prot_info,aes(x = log10(sums),y = complete)) + geom_point() + 
#   theme_bw() + ggtitle('No normalization')+ xlab('Mean Protein Intensity') + ylab('# Complete')+ theme(axis.title.x = element_text(size = 15),axis.title.y = element_text(size = 15),axis.text.x = element_text(size = 10),axis.text.y = element_text(size = 10))
# 
# Norm_quality_post_prot <-ggplot(prot_info,aes(x = (sum_norm),y = complete)) + geom_point() + 
#   theme_bw()+ggtitle('With normalization')+ xlab('Mean Protein Intensity') + ylab('# Complete')+ theme(axis.title.x = element_text(size = 15),axis.title.y = element_text(size = 15),axis.text.x = element_text(size = 10),axis.text.y = element_text(size = 10))
# 
# 
# Norm_quality_post_prot_var <-ggplot(prot_info,aes(x = log2(vars),y = complete)) + geom_point() + theme_bw() +ggtitle('With normalization')+ xlab('Protein Variance') + ylab('# Complete')+ theme(axis.title.x = element_text(size = 15),axis.title.y = element_text(size = 15),axis.text.x = element_text(size = 10),axis.text.y = element_text(size = 10))
# 
#   
#   #annotate("text", x=.75, y=3,size=12, label= paste0("Cor = ", round(cor(log10(prot_info$sums),log10(prot_info$vars_no_norm),use = 'pairwise.complete.obs'),digits = 3)))
# 
# Norm_quality_pre_prot + Norm_quality_post_prot + Norm_quality_post_prot_var

```


